apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: testplayground
  namespace: paw
  labels:
    team: paw
  annotations:
    dcat.data.nav.no/title: "Test topic"
    dcat.data.nav.no/description: "Test topic for testing og lek"

spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3 # see min/max requirements
    retentionBytes: -1 # -1 means unlimited
    retentionHours: 168 # -1 means unlimited
  acl:
    - team: paw
      application: aia-backend
      access: readwrite # read, write, readwrite
    - team: paw
      application: jonas.maccyber.enge@nav.no
      access: read
